# Site
title:              Wireles RC Adapter
bio:                'Arduino USB-Joystick adapter for RC receivers with PWM and PPM modulations up to 8 channels.'
description:        "."
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false
locale:             en_US
url:                http://wireless-rc-adapter.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
gems:
 - jekyll-sitemap

#jekyll-mentions:
#    base_url: http://wireless-rc-adapter.github.io

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
