# Site
title:              Wireless RC Adapter
bio:                'A blazing fast Arduino USB adapter for RC receivers up to 8 channels!'
description:        "Making possible to play wireless as it meant to be, while supporting **16bit resolution* without any lag. There is no need to hook the radio transmitter with cables to the simulator anymore, just plug it in the **USB port and play*. It is compatible with a wide range of devices, like the ones running **Windows, Mac, Linux* or **Android/iOS*, literally almost anything whats have an USB port. Aimed to be fast and simple to use."
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false
locale:             en_US
url:                https://wireless-rc-adapter.github.io
google_analytics:   UA-115417832-2

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
gems:
 - jekyll-sitemap

#jekyll-mentions:
#    base_url: https://wireless-rc-adapter.github.io

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
